version: '3.8'

services:
  db:
    image: mariadb:10.6
    volumes:
      - dmitry-wp-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dmitry_db_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:6.0
    ports:
      - "2067:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  dmitry-wp-data:
